export const ACCENTS = {
  red: {
    text: "text-red-400",
    textDim: "text-red-600",
    tagBorder: "border-red-900/40",
    cardBorder: "hover:border-red-900/70",
    cardBg: "hover:bg-red-950/40",
    titleHover: "group-hover:text-red-400",
    proseLink: "prose-a:text-red-400",
    pageBg: "bg-red-950/30",
    backHover: "hover:text-red-400",
    mobileToc: "hover:text-red-400",
  },
  orange: {
    text: "text-orange-400",
    textDim: "text-orange-600",
    tagBorder: "border-orange-900/40",
    cardBorder: "hover:border-orange-900/70",
    cardBg: "hover:bg-orange-950/40",
    titleHover: "group-hover:text-orange-400",
    proseLink: "prose-a:text-orange-400",
    pageBg: "bg-orange-950/30",
    backHover: "hover:text-orange-400",
    mobileToc: "hover:text-orange-400",
  },
  amber: {
    text: "text-amber-400",
    textDim: "text-amber-600",
    tagBorder: "border-amber-900/40",
    cardBorder: "hover:border-amber-900/70",
    cardBg: "hover:bg-amber-950/40",
    titleHover: "group-hover:text-amber-400",
    proseLink: "prose-a:text-amber-400",
    pageBg: "bg-amber-950/30",
    backHover: "hover:text-amber-400",
    mobileToc: "hover:text-amber-400",
  },
  yellow: {
    text: "text-yellow-400",
    textDim: "text-yellow-600",
    tagBorder: "border-yellow-900/40",
    cardBorder: "hover:border-yellow-900/70",
    cardBg: "hover:bg-yellow-950/40",
    titleHover: "group-hover:text-yellow-400",
    proseLink: "prose-a:text-yellow-400",
    pageBg: "bg-yellow-950/30",
    backHover: "hover:text-yellow-400",
    mobileToc: "hover:text-yellow-400",
  },
  lime: {
    text: "text-lime-400",
    textDim: "text-lime-600",
    tagBorder: "border-lime-900/40",
    cardBorder: "hover:border-lime-900/70",
    cardBg: "hover:bg-lime-950/40",
    titleHover: "group-hover:text-lime-400",
    proseLink: "prose-a:text-lime-400",
    pageBg: "bg-lime-950/30",
    backHover: "hover:text-lime-400",
    mobileToc: "hover:text-lime-400",
  },
  green: {
    text: "text-green-400",
    textDim: "text-green-600",
    tagBorder: "border-green-900/40",
    cardBorder: "hover:border-green-900/70",
    cardBg: "hover:bg-green-950/40",
    titleHover: "group-hover:text-green-400",
    proseLink: "prose-a:text-green-400",
    pageBg: "bg-green-950/30",
    backHover: "hover:text-green-400",
    mobileToc: "hover:text-green-400",
  },
  emerald: {
    text: "text-emerald-400",
    textDim: "text-emerald-600",
    tagBorder: "border-emerald-900/40",
    cardBorder: "hover:border-emerald-900/70",
    cardBg: "hover:bg-emerald-950/40",
    titleHover: "group-hover:text-emerald-400",
    proseLink: "prose-a:text-emerald-400",
    pageBg: "bg-emerald-950/30",
    backHover: "hover:text-emerald-400",
    mobileToc: "hover:text-emerald-400",
  },
  teal: {
    text: "text-teal-400",
    textDim: "text-teal-600",
    tagBorder: "border-teal-900/40",
    cardBorder: "hover:border-teal-900/70",
    cardBg: "hover:bg-teal-950/40",
    titleHover: "group-hover:text-teal-400",
    proseLink: "prose-a:text-teal-400",
    pageBg: "bg-teal-950/30",
    backHover: "hover:text-teal-400",
    mobileToc: "hover:text-teal-400",
  },
  cyan: {
    text: "text-cyan-400",
    textDim: "text-cyan-600",
    tagBorder: "border-cyan-900/40",
    cardBorder: "hover:border-cyan-900/70",
    cardBg: "hover:bg-cyan-950/40",
    titleHover: "group-hover:text-cyan-400",
    proseLink: "prose-a:text-cyan-400",
    pageBg: "bg-cyan-950/30",
    backHover: "hover:text-cyan-400",
    mobileToc: "hover:text-cyan-400",
  },
  sky: {
    text: "text-sky-400",
    textDim: "text-sky-600",
    tagBorder: "border-sky-900/40",
    cardBorder: "hover:border-sky-900/70",
    cardBg: "hover:bg-sky-950/40",
    titleHover: "group-hover:text-sky-400",
    proseLink: "prose-a:text-sky-400",
    pageBg: "bg-sky-950/30",
    backHover: "hover:text-sky-400",
    mobileToc: "hover:text-sky-400",
  },
  blue: {
    text: "text-blue-400",
    textDim: "text-blue-600",
    tagBorder: "border-blue-900/40",
    cardBorder: "hover:border-blue-900/70",
    cardBg: "hover:bg-blue-950/40",
    titleHover: "group-hover:text-blue-400",
    proseLink: "prose-a:text-blue-400",
    pageBg: "bg-blue-950/30",
    backHover: "hover:text-blue-400",
    mobileToc: "hover:text-blue-400",
  },
  indigo: {
    text: "text-indigo-400",
    textDim: "text-indigo-600",
    tagBorder: "border-indigo-900/40",
    cardBorder: "hover:border-indigo-900/70",
    cardBg: "hover:bg-indigo-950/40",
    titleHover: "group-hover:text-indigo-400",
    proseLink: "prose-a:text-indigo-400",
    pageBg: "bg-indigo-950/30",
    backHover: "hover:text-indigo-400",
    mobileToc: "hover:text-indigo-400",
  },
  violet: {
    text: "text-violet-400",
    textDim: "text-violet-600",
    tagBorder: "border-violet-900/40",
    cardBorder: "hover:border-violet-900/70",
    cardBg: "hover:bg-violet-950/40",
    titleHover: "group-hover:text-violet-400",
    proseLink: "prose-a:text-violet-400",
    pageBg: "bg-violet-950/30",
    backHover: "hover:text-violet-400",
    mobileToc: "hover:text-violet-400",
  },
  purple: {
    text: "text-purple-400",
    textDim: "text-purple-600",
    tagBorder: "border-purple-900/40",
    cardBorder: "hover:border-purple-900/70",
    cardBg: "hover:bg-purple-950/40",
    titleHover: "group-hover:text-purple-400",
    proseLink: "prose-a:text-purple-400",
    pageBg: "bg-purple-950/30",
    backHover: "hover:text-purple-400",
    mobileToc: "hover:text-purple-400",
  },
  fuchsia: {
    text: "text-fuchsia-400",
    textDim: "text-fuchsia-600",
    tagBorder: "border-fuchsia-900/40",
    cardBorder: "hover:border-fuchsia-900/70",
    cardBg: "hover:bg-fuchsia-950/40",
    titleHover: "group-hover:text-fuchsia-400",
    proseLink: "prose-a:text-fuchsia-400",
    pageBg: "bg-fuchsia-950/30",
    backHover: "hover:text-fuchsia-400",
    mobileToc: "hover:text-fuchsia-400",
  },
  pink: {
    text: "text-pink-400",
    textDim: "text-pink-600",
    tagBorder: "border-pink-900/40",
    cardBorder: "hover:border-pink-900/70",
    cardBg: "hover:bg-pink-950/40",
    titleHover: "group-hover:text-pink-400",
    proseLink: "prose-a:text-pink-400",
    pageBg: "bg-pink-950/30",
    backHover: "hover:text-pink-400",
    mobileToc: "hover:text-pink-400",
  },
  rose: {
    text: "text-rose-400",
    textDim: "text-rose-600",
    tagBorder: "border-rose-900/40",
    cardBorder: "hover:border-rose-900/70",
    cardBg: "hover:bg-rose-950/40",
    titleHover: "group-hover:text-rose-400",
    proseLink: "prose-a:text-rose-400",
    pageBg: "bg-rose-950/30",
    backHover: "hover:text-rose-400",
    mobileToc: "hover:text-rose-400",
  },
} as const;

export type AccentKey = keyof typeof ACCENTS;

export function getAccent(accent?: string): (typeof ACCENTS)[AccentKey] {
  return ACCENTS[(accent as AccentKey) ?? "emerald"] ?? ACCENTS.emerald;
}
